### Get GitHub repositories
@owner = github

# @name repos
GET https://api.github.com/orgs/{{owner}}/repos


### Get Issues
@repo = {{repos.response.body.$.[0].name}}
GET https://api.github.com/repos/{{owner}}/{{repo}}/issues
